### ISSUE TITLE
Index out of bounds panic in CLI `get` command if request fails

### ISSUE THREAD

**Issue by naglis** [warthog618/gpiocdev-rs#11]
using `gpiocdev-cli = "0.5.1"` I am getting:
> thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0'

coming from [here](https://github.com/warthog618/gpiocdev-rs/blob/de006b0b6d2d64a608ed7e41d3413d9ab2678795/cli/src/get.rs#L127).

IIUC it is because the line request [failed](https://github.com/warthog618/gpiocdev-rs/blob/de006b0b6d2d64a608ed7e41d3413d9ab2678795/cli/src/get.rs#L112) (in my case it was because device was busy) and so the request [was not pushed onto `requests`](https://github.com/warthog618/gpiocdev-rs/blob/de006b0b6d2d64a608ed7e41d3413d9ab2678795/cli/src/get.rs#L109) and so there was a mismatch between the lengths of [`r.chips`](https://github.com/warthog618/gpiocdev-rs/blob/de006b0b6d2d64a608ed7e41d3413d9ab2678795/cli/src/get.rs#L125) and [`requests`](https://github.com/warthog618/gpiocdev-rs/blob/de006b0b6d2d64a608ed7e41d3413d9ab2678795/cli/src/get.rs#L127) in the second loop.

**Comment by warthog618** [comment]
Yeah, that is broken as you describe.
I'll have a look at it.

**Comment by warthog618** [comment]
Fix released in cli v0.5.2.
