### ISSUE TITLE
Remove chrono dependency

### ISSUE THREAD

**Issue by mattfbacon** [warthog618/gpiocdev-rs#14]
Timestamp can just use SystemTime.

```diff
diff --git a/lib/src/lib.rs b/lib/src/lib.rs
index 389494b..88f5100 100644
--- a/lib/src/lib.rs
+++ b/lib/src/lib.rs
@@ -409,20 +409,18 @@ impl fmt::Display for AbiVersion {

 /// A moment in time in UTC.
 #[derive(Clone, Debug, Eq, PartialEq)]
-pub struct Timestamp(DateTime<Utc>);
+pub struct Timestamp(SystemTime);

 impl Timestamp {
     /// Create a Timestamp from the number of nanoseconds.
     ///
     /// Suitable for **CLOCK_REALTIME** clock sources.
     pub fn from_nanos(t: u64) -> Self {
-        let sec = (t / 1000000000) as i64;
-        let nsec = (t as u32) % 1000000000;
-        Timestamp(Utc.timestamp_opt(sec, nsec).unwrap())
+        Self(SystemTime::UNIX_EPOCH + Duration::from_nanos(t))
     }
 }

-impl From<Timestamp> for DateTime<Utc> {
+impl From<Timestamp> for SystemTime {
     fn from(ts: Timestamp) -> Self {
         ts.0
     }
```

**Comment by warthog618** [comment]
The patch does not completely remove the dependency.  The use and Cargo.toml need to be updated as well.

What is the issue with chrono that makes the dependency a problem?

I am open to removing dependencies that don't add much, and the chrono DateTime is mainly there for the cli that displays local time, but that could create a DateTime from a SystemTime instead.

**Comment by mattfbacon** [comment]
> The patch does not completely remove the dependency. 

Indeed, it is for explanatory purposes. I can make a full PR if we go through with it.

> What is the issue with chrono

It's unnecessary and fairly heavy.

> Or just drop the Timestamp class completely 

Sure, would that be preferable?

**Comment by warthog618** [comment]
> > Or just drop the Timestamp class completely
> 
> Sure, would that be preferable?

That works for me.  There will have to be a version bump either way, and the SystemTime version is little better than the raw nanos, so why bother?  I've got a patch locally that does that, and it turns out that the cli doesn't even use Timestamp after all - it conditionally does the conversion using the nanos.

**Comment by warthog618** [comment]
Side note - if there is any call for chrono in the future it can be added behind a non-default feature to keep the default dependencies minimal.
