### ISSUE TITLE
Device or resource busy

### ISSUE THREAD

**Issue by melkir** [warthog618/gpiocdev-rs#9]
I'm trying to use this lib while another process access to the GPIO.
By doing so, I'm receiving the following message:
```
UapiError(GetLine, Os(Errno { code: 16, description: Some("Device or resource busy") }))
```
Using `RPi.GPIO` or `gpiozero` from the python community, you get a warning and you've the possibility to ignore it.
```
RuntimeWarning: This channel is already in use, continuing anyway. Use GPIO.setwarnings(False) to disable warnings
```
Is there anything similar that could be done on this project?

**Comment by warthog618** [comment]
Can't be done - the use of GPIO lines via the uAPI is exclusive, so only one process can read or write the line value.
The kernel policy is that a line is not a shared resource - at any one time it can only have one owner, and that is reflected in the uAPI.  There is no way to override that.

What RPi.GPIO etc do is play with the hardware directly themselves, without the knowledge of the kernel, and so they can happily ignore any contention.  And that only works on Pis, not general hardware, as they decided to expose the hardware to userspace via /dev/gpiomem, cos they didn't have kernel drivers ready for the Pi at the time.  And now we're stuck with it.

If you need to share the line value between processes then one process should monitor the line and share the value with the others.

Or find a Rust library that is happy to do unsafe things with the Pi hardware.

**Comment by melkir** [comment]
Thanks @warthog618 for the detailed explainations, that's really appreciated!
